"""fix permission

Revision ID: 17e0f2ca1150
Revises: 9a66f5ad7e16
Create Date: 2025-04-13 09:47:59.602600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e0f2ca1150'
down_revision: Union[str, None] = '9a66f5ad7e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'page',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_constraint('permissions_page_key', 'permissions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('permissions_page_key', 'permissions', ['page'])
    op.alter_column('permissions', 'page',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
