"""notif

Revision ID: 7ab8e6502fc7
Revises: 8a1045e2a842
Create Date: 2025-04-09 11:48:17.922690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab8e6502fc7'
down_revision: Union[str, None] = '8a1045e2a842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('essence', sa.String(length=255), nullable=False))
    op.drop_column('notifications', 'repeat')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('repeat', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'essence')
    # ### end Alembic commands ###
