"""chat_ids

Revision ID: 8a1045e2a842
Revises: 14fcf503a6f0
Create Date: 2025-04-09 11:26:14.552832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a1045e2a842'
down_revision: Union[str, None] = '14fcf503a6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_whatsapp_chats_id')
    op.add_column('users', sa.Column('chat_id_whatsapp', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('chat_id_telegram', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id_telegram')
    op.drop_column('users', 'chat_id_whatsapp')
    op.create_table('ai_whatsapp_chats_id',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ai_whatsapp_chats_id_pkey')
    )
    # ### end Alembic commands ###
