"""Update permissions

Revision ID: 9a66f5ad7e16
Revises: 33d529cda799
Create Date: 2025-04-13 09:45:07.904012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a66f5ad7e16'
down_revision: Union[str, None] = '33d529cda799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('page', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'permissions', ['page'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_column('permissions', 'page')
    # ### end Alembic commands ###
